Misc build fix due to the API version change in ixion.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -16,6 +16,6 @@ dist-hook:
 	then \
 		git log --date=short --pretty="format:@%cd  %an  <%ae>  [%H]%n%n%s%n%n%e%b" | sed -e "s|^\([^@]\)|\t\1|" -e "s|^@||" >$(distdir)/ChangeLog \
 	else \
-		echo A git clone is required to generate a ChangeLog >&2; \
+		echo "A git clone is required to generate a ChangeLog" >&2; \
 	fi
 
